services:

  trainer-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: trainer
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      - postgres

  trainer-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: trainer
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    depends_on:
      - postgres

  trainings-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: trainings
      GOCACHE: /go-cache
    depends_on:
      - postgres

  users-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal
    ports:
      - "127.0.0.1:3002:$PORT"
    environment:
      SERVICE: users
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - postgres

  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal
    ports:
      - "127.0.0.1:3020:$PORT"
    environment:
      SERVICE: users
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_ddd_template_dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
